name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/lukaj-test:latest
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --all-features --verbose
      - run: cargo test --all-features --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts ${{ matrix.toolchain }}
          path: target/tmp/*
          retention-days: 7
          if-no-files-found: error

  publish:
    name: Publish release
    needs:
    - build_and_test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/lukaj-test:latest
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - name: Push to crates.io
      run: cargo publish --all-features
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
